AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: GroupingUnit Executor

Globals:
  Function:
    Runtime: java11
    MemorySize: 2048
    Timeout: 29

Resources:
  GUExecutorApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
  GUExecutorFunction:
    Type: AWS::Serverless::Function
    Properties:
      # Need to change the folder structure for this
      Handler: guexecutor.LambdaHandler
      CodeUri: GUExecutorFunction
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
          AWS_SERVERLESS_JAVA_CONTAINER_INIT_GRACE_TIME: 500
          FLOW_DEFINITION_FILE: /opt/snapshot.json
      AutoPublishAlias: live
      SnapStart:
        ApplyOn: PublishedVersions
      Layers:
        - !Ref ConfLayer
        - !Ref NarLayer
      Events:
        ApiEvents:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref GUExecutorApi

  ConfLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: configs
      Description: configs for the node
      ContentUri: configs/
      RetentionPolicy: Retain

  NarLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: nars
      Description: NAR files for NiFi
      ContentUri: nars/
      RetentionPolicy: Retain

Outputs:
  GUExecutorEndpoint:
    Description: API Gateway GUExecutor Endpoint
    Value:
      Fn::Sub: https://${GUExecutorApi}.execute-api.${AWS::Region}.amazonaws.com/prod/
